build:
  main: cmd/joy/main.go
  binary: joy
  ldflags: -s -w
    -X github.com/matthewmueller/joy/internal/version.Version={{.Version}}
    -X main.commit={{.Commit}} 
    -X main.date={{.Date}}
    -X github.com/matthewmueller/joy/internal/env.awsAccessKey={{.Env.JOY_AWS_ACCESS_ID}}
    -X github.com/matthewmueller/joy/internal/env.awsSecretKey={{.Env.JOY_AWS_SECRET_ACCESS_KEY}}
    -X github.com/matthewmueller/joy/internal/env.awsRegion={{.Env.JOY_AWS_REGION}}
    -X github.com/matthewmueller/joy/internal/env.firehoseStream={{.Env.JOY_AWS_FIREHOSE_STREAM}}
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
  goarch:
    - amd64
    - 386
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^refactor'
